
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class MainGUI extends javax.swing.JFrame implements Runnable {
    Connection conn,co,c = null;
    Statement st,s,ss,sst = null;
    
    ResultSet rset = null;
    ResultSet rs,r =null;
    private static int old=-1;
    private static int o=-1;
    static String url;
    static String db;
    static String pas;
    static String user;
    static String cd;
    /**
     * Creates new form MainGUI
     */
    public MainGUI(String us,String abc,String cdf,String xx) {
        initComponents();
        jLabel3.setText(us);
        user=us;
        url=abc;
        db=cdf;
        pas="";
        update();
        cd = xx;
        setLocationRelativeTo(null);
        
    }
    public void update() {
      new Thread(this).start();
     
      }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chat Client");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 10, 110, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 297, 420);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 490, 297, 40);

        jTextArea3.setColumns(20);
        jTextArea3.setEditable(false);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(320, 60, 110, 420);

        jButton2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jButton2.setText("Send");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 490, 110, 40);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Online");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 40, 36, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 200, 20);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 10, 0, 0);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 10, 0, 0);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Green", "Red", "Blue", "Yellow" }));
        jComboBox1.setSelectedIndex(2);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(224, 12, 78, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
@Override
      public void run() {
           
           int i=1;
           int a=100;
           
           while (i<=a){
             
              try {
                  //for online list
                  
                  c = DriverManager.getConnection(url,db,pas);
                  
                  String SiiQL = "SELECT MAX(id) FROM online  " ;
                  ss = c.createStatement();
      	          r = ss.executeQuery(SiiQL);
                  if(r.next()){
                      
                       String oid=r.getString("MAX(id)"); 
                     int y=Integer.parseInt(oid);
                     if(y != o){
                         
                         try{
                              jTextArea3.setText("");
                              SiiQL = "SELECT * FROM online  " ;
                                   sst = c.createStatement();
      	                           r = sst.executeQuery(SiiQL);   
                         
                        while (r.next()){
                           
                                  
                                   jTextArea3.append(r.getString("un")+"\n");
                
           
                       } 
                    }
                         catch(Exception e) {
                          System.out.println("err 1");
                      } 
                         
                       o=y;    
                     }
                      
                  } 
                   //for getting message
                  try{
                  conn = DriverManager.getConnection(url,db,pas);
                  String SQL = "SELECT MAX(ID) FROM Mess  " ;
                  st = conn.createStatement();
      	          rset = st.executeQuery(SQL);
                  //Setting colour
                  String colour=jComboBox1.getSelectedItem().toString();
                  if (colour.equals("Green")){
                  
                  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Main.jpg")));
                  }
                  if (colour.equals("Red")){
                  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Main_r.jpg")));
                  }
                  if (colour.equals("Blue")){
                
                  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Main_b.jpg")));
                  }
                  if (colour.equals("Yellow")){
                
                  jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Main_y.jpg")));
                  }
                  
                  //Setting colour ends
                  if(rset.next()){
                     String id=rset.getString("MAX(id)"); 
                     int x=Integer.parseInt(id);
                     
                  
                  
                      if(x != old){
                          try{
                                   jTextArea1.setText("");
                                   
                                   String SiQL = "SELECT * FROM Mess WHERE ID>"+cd ;
                                   s = conn.createStatement();
      	                           rs = s.executeQuery(SiQL);
                                while (rs.next()){
                                 
                                    
                                    
                                    jTextArea1.append(rs.getString("Username").toUpperCase()+":"+rs.getString("Message")+"\n");
                                    jTextArea1.setCaretPosition(jTextArea1.getText().length() - 1);
                                    
                                 
                                 }
                          }
                          catch(Exception e){
                              System.out.println("error 2");
                                
                          }
                          old=x;
                      }
                      
                   } 
                  }
                  catch(Exception e){
                      System.out.println("");
                  }
        
              }
           catch(Exception e) {
            System.out.println();
            }
             
            } 
          
            
            
      } 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try{
              
            co = DriverManager.getConnection(url,db,pas);
                  String SQL = "DELETE FROM online where un='"+jLabel3.getText()+"'" ;
                  s = co.createStatement();
      	          int n = s.executeUpdate(SQL);
                  System.exit(0);
            }
        catch(Exception e) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            
            //For Inserting
            
            conn = DriverManager.getConnection(url,db,pas);
            String SIQL = "INSERT INTO Mess (Username,Message) "+
                        "VALUES('"+jLabel3.getText()+"','" + jTextArea2.getText()+"')";
                                   
            s = conn.createStatement();
            int n = s.executeUpdate(SIQL);
            jTextArea2.setText("");
           
            if (n<0) {
               JOptionPane.showMessageDialog(null, "Message not sent");
            }
              
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        MainGUI may = new MainGUI(user,url,db,cd);
           may.setVisible(true);
           may.update();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    // End of variables declaration//GEN-END:variables
}
