
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class SignUpGUI extends javax.swing.JFrame {
  Connection conn,co = null;
    Statement st,s = null;
    
    ResultSet rset = null;
    ResultSet rs =null;
    static String url,db,pas;
    /**
     * Creates new form SignUpGUI
     */
    public SignUpGUI(String abc,String cdf) {
        initComponents();
        url=abc;
        db=cdf;
        pas="";
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chat Client");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(176, 20, 54, 19);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(75, 76, 59, 18);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(176, 76, 128, 20);

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(77, 130, 57, 18);
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(176, 130, 128, 20);

        jButton1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 200, 93, 49);

        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(176, 105, 128, 19);

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(176, 161, 200, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login and sign.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, -10, 400, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            co = DriverManager.getConnection(url,db,pas);
            String SiQL = "SELECT * from reg WHERE Username='" + jTextField1.getText() + "'";

            s = co.createStatement();
            rset = s.executeQuery(SiQL);
            if (rset.next()) {
                jLabel4.setText("");
                String chk = rset.getString("Username");
                if (chk.equals(jTextField1.getText()) ) {
                    jLabel5.setText("");
                    jLabel4.setText("Username Exists");
                }
                if (jTextField1.getText().equals("") )
                {
                    jLabel4.setText("");
                    jLabel5.setText("Please do not leave the fields empty");
                    
                }
                
            } else {
                if (jPasswordField1.getText().equals("")){
                   jLabel4.setText("");
                   jLabel5.setText("Please do not leave fields empty!!"); 
                }
                else{
                conn = DriverManager.getConnection(url,db,pas);
                String SQL = "INSERT INTO REG (Username,Password) "
                        + "VALUES('" + jTextField1.getText() + "', '" + jPasswordField1.getText() + "') ";

                st = conn.createStatement();
                int n = st.executeUpdate(SQL);
                JOptionPane.showMessageDialog(null, "Registered,you may now login");
                this.setVisible(false);
                this.dispose();
                }
            }











        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());


        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SignUpGUI(url,db).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
